In [1]:
import runpod
import boto3

/home/jorge/miniconda3/envs/ml-platform/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [ ]:
import json
import os

# Configura tu API Key (puedes obtenerla en la configuración de tu cuenta RunPod)
runpod.api_key = ""

def obtener_precios_gpu(gpu_name):
    try:
        # Obtiene detalles técnicos y de mercado para la GPU especificada
        gpu_info = runpod.get_gpu(gpu_name)
        
        print(f"--- Precios para {gpu_info['displayName']} ---")
        print(f"Precio Community Cloud: ${gpu_info['communityPrice']}/hr")
        print(f"Precio Secure Cloud: ${gpu_info['securePrice']}/hr")

        print(json.dumps(gpu_info, indent=2))

            
    except Exception as e:
        print(f"Error al obtener datos: {e}")

# Ejemplo de uso
obtener_precios_gpu("NVIDIA RTX 4090")

Error al obtener datos: No GPU found with the specified ID, run runpod.get_gpus() to get a list of all GPUs

In [ ]:
lista_gpus_low = [
    "NVIDIA A40",
    "NVIDIA GeForce RTX 4090",
    "NVIDIA GeForce RTX 5090",
    "NVIDIA L4",
    "NVIDIA RTX PRO 4500 Blackwell"
]

lista_gpus_medium = [
    "NVIDIA L40S",
    "NVIDIA RTX 6000 Ada Generation",
    "NVIDIA RTX PRO 6000 Blackwell Server Edition",
    "NVIDIA L40"
]

lista_gpus_high = [
    "NVIDIA H100 80GB HBM3",   # H100 SXM
    "NVIDIA H100 PCIe",
    "NVIDIA H100 NVL",
    "NVIDIA H200 NVL"
]

In [3]:
all_gpus = runpod.get_gpus()

In [4]:
obtener_precios_gpu("NVIDIA RTX 2000 Ada Generation")

--- Precios para RTX 2000 Ada ---
Precio Community Cloud: $0.5/hr
Precio Secure Cloud: $0.24/hr
{
  "maxGpuCount": 8,
  "id": "NVIDIA RTX 2000 Ada Generation",
  "displayName": "RTX 2000 Ada",
  "manufacturer": "Nvidia",
  "memoryInGb": 16,
  "cudaCores": 0,
  "secureCloud": true,
  "communityCloud": false,
  "securePrice": 0.24,
  "communityPrice": 0.5,
  "oneMonthPrice": null,
  "threeMonthPrice": 0.196,
  "oneWeekPrice": null,
  "communitySpotPrice": null,
  "secureSpotPrice": 0.14,
  "lowestPrice": {
    "minimumBidPrice": null,
    "uninterruptablePrice": 0.5
  }
}

In [1]:
import subprocess
import json

result = subprocess.run(["sky", "show-gpus", "RTX2000-Ada"], capture_output=True, text=True)
print(result.stdout)

GPU          QTY  CLOUD   INSTANCE_TYPE          DEVICE_MEM  vCPUs  HOST_MEM  HOURLY_PRICE  HOURLY_SPOT_PRICE  REGION
RTX2000-Ada  1.0  RunPod  1x_RTX2000-Ada_SECURE  0GB         6      31GB      $ 0.240       $ 0.140            CA
RTX2000-Ada  2.0  RunPod  2x_RTX2000-Ada_SECURE  0GB         12     62GB      $ 0.480       $ 0.280            CA
RTX2000-Ada  3.0  RunPod  3x_RTX2000-Ada_SECURE  0GB         18     93GB      $ 0.720       $ 0.420            CA
RTX2000-Ada  4.0  RunPod  4x_RTX2000-Ada_SECURE  0GB         24     124GB     $ 0.960       $ 0.560            CA
RTX2000-Ada  5.0  RunPod  5x_RTX2000-Ada_SECURE  0GB         30     155GB     $ 1.200       $ 0.700            CA
RTX2000-Ada  6.0  RunPod  6x_RTX2000-Ada_SECURE  0GB         36     186GB     $ 1.440       $ 0.840            CA
RTX2000-Ada  7.0  RunPod  7x_RTX2000-Ada_SECURE  0GB         42     217GB     $ 1.680       $ 0.980            CA
RTX2000-Ada  8.0  RunPod  8x_RTX2000-Ada_SECURE  0GB         48     248GB     $ 1.920       $ 1.120            CA

In [7]:
import pandas as pd
import re

data = result.stdout

# Regex para capturar columnas correctamente
pattern = re.compile(
    r"(\S+)\s+"      # GPU
    r"([\d.]+)\s+"   # QTY
    r"(\S+)\s+"      # CLOUD
    r"(\S+)\s+"      # INSTANCE_TYPE
    r"(\S+)\s+"      # DEVICE_MEM
    r"(\d+)\s+"      # vCPUs
    r"(\S+)\s+"      # HOST_MEM
    r"\$\s*([\d.]+)\s+"  # HOURLY_PRICE
    r"\$\s*([\d.]+)\s+"  # HOURLY_SPOT_PRICE
    r"(\S+)"         # REGION
)

rows = [m.groups() for m in pattern.finditer(data)]
columns = ["GPU","QTY","CLOUD","INSTANCE_TYPE","DEVICE_MEM","vCPUs","HOST_MEM","HOURLY_PRICE","HOURLY_SPOT_PRICE","REGION"]

df = pd.DataFrame(rows, columns=columns)

# Convertir tipos
df['QTY'] = df['QTY'].astype(float)
df['vCPUs'] = df['vCPUs'].astype(int)
df['HOURLY_PRICE'] = df['HOURLY_PRICE'].astype(float)
df['HOURLY_SPOT_PRICE'] = df['HOURLY_SPOT_PRICE'].astype(float)

df

,GPU,QTY,CLOUD,INSTANCE_TYPE,DEVICE_MEM,vCPUs,HOST_MEM,HOURLY_PRICE,HOURLY_SPOT_PRICE,REGION
0,RTX2000-Ada,1.0,RunPod,1x_RTX2000-Ada_SECURE,0GB,6,31GB,0.24,0.14,CA
1,RTX2000-Ada,2.0,RunPod,2x_RTX2000-Ada_SECURE,0GB,12,62GB,0.48,0.28,CA
2,RTX2000-Ada,3.0,RunPod,3x_RTX2000-Ada_SECURE,0GB,18,93GB,0.72,0.42,CA
3,RTX2000-Ada,4.0,RunPod,4x_RTX2000-Ada_SECURE,0GB,24,124GB,0.96,0.56,CA
4,RTX2000-Ada,5.0,RunPod,5x_RTX2000-Ada_SECURE,0GB,30,155GB,1.20,0.70,CA
5,RTX2000-Ada,6.0,RunPod,6x_RTX2000-Ada_SECURE,0GB,36,186GB,1.44,0.84,CA
6,RTX2000-Ada,7.0,RunPod,7x_RTX2000-Ada_SECURE,0GB,42,217GB,1.68,0.98,CA
7,RTX2000-Ada,8.0,RunPod,8x_RTX2000-Ada_SECURE,0GB,48,248GB,1.92,1.12,CA

In [3]:
import requests
import os

API_KEY = os.getenv("RUNPOD_API_KEY")

url = f"https://api.runpod.io/graphql?api_key={API_KEY}"

query = {
    "query": """
    query {
      gpuTypes(input: { id: "NVIDIA RTX 4000 Ada Generation" }) {
        id
        displayName
        lowestPrice(
          input: {
            secureCloud: true,
            gpuCount: 1,
            minVcpuCount: 2,
            minMemoryInGb: 8,
            minDisk: 0,
            dataCenterId: null,
            globalNetwork: false,
            compliance: null
          }
        ) {
          stockStatus
          availableGpuCounts
          maxUnreservedGpuCount
          uninterruptablePrice
          minimumBidPrice
        }
      }
    }
    """
}

headers = {
    "Content-Type": "application/json"
}

response = requests.post(url, json=query, headers=headers)

print(response.status_code)
print(response.json())

200
{'data': {'gpuTypes': [{'id': 'NVIDIA RTX 4000 Ada Generation', 'displayName': 'RTX 4000 Ada', 'lowestPrice': {'stockStatus': 'Low', 'availableGpuCounts': [1], 'maxUnreservedGpuCount': 1, 'uninterruptablePrice': 0.26, 'minimumBidPrice': 0.19}}]}}

In [ ]:
from vastai_sdk import VastAI

vast_sdk = VastAI(api_key='')

# Get all available GPU names
output = vast_sdk.search_offers(gpu_name="RTX_5090", rented=False, rentable=True, geolocation="US")
print(output)

[{'id': 30409089, 'ask_contract_id': 30409089, 'bundle_id': 2018009266, 'bundled_results': None, 'bw_nvlink': 0.0, 'compute_cap': 1200, 'cpu_arch': 'amd64', 'cpu_cores': 64, 'cpu_cores_effective': 64.0, 'cpu_ghz': 5.352, 'cpu_name': 'AMD Ryzen Threadripper PRO 7975WX 32-Cores', 'cpu_ram': 128280, 'credit_discount_max': 0.0, 'cuda_max_good': 13.0, 'direct_port_count': 99, 'disk_bw': 4460.0, 'disk_name': 'AMI Virtual', 'disk_space': 1309.0, 'dlperf': 398.01470754705707, 'dlperf_per_dphtotal': 595.8634379689793, 'dph_base': 0.6666666666666666, 'dph_total': 0.667962962962963, 'driver_version': '580.95.05', 'driver_vers': 580095005, 'duration': 1496348.28014493, 'end_date': 1775466433.0140142, 'external': None, 'flops_per_dphtotal': 322.117979484336, 'geolocation': 'Latvia, LV', 'geolocode': 1165216004, 'gpu_arch': 'nvidia', 'gpu_display_active': True, 'gpu_frac': 1.0, 'gpu_ids': [155078, 155079], 'gpu_lanes': 16, 'gpu_mem_bw': 1455.3, 'gpu_name': 'RTX 5090', 'gpu_ram': 32607, 'gpu_total_ram': 65214, 'gpu_max_power': 575.0, 'gpu_max_temp': 50.0, 'has_avx': 1, 'host_id': 350561, 'hosting_type': 0, 'hostname': None, 'inet_down': 944.7, 'inet_down_cost': 3.90625e-06, 'inet_up': 941.4, 'inet_up_cost': 5.208333333333333e-06, 'is_bid': False, 'logo': '/static/logos/vastai_small2.png', 'machine_id': 47391, 'min_bid': 0.6666666666666666, 'mobo_name': 'Pro WS WRX90E-SAGE SE', 'num_gpus': 2, 'os_version': '24.04', 'pci_gen': 5.0, 'pcie_bw': 54.3, 'public_ipaddr': '80.232.223.109', 'reliability': 0.9981699, 'reliability_mult': 0.9820214, 'rentable': True, 'rented': False, 'score': 567.4022625753754, 'start_date': 1773967073.137, 'static_ip': True, 'storage_cost': 0.18666666666666665, 'storage_total_cost': 0.001296296296296296, 'total_flops': 215.16287999999997, 'verification': 'verified', 'vericode': 1, 'vram_costperhour': 0.010468099896750186, 'webpage': None, 'vms_enabled': False, 'expected_reliability': 0.0, 'is_vm_deverified': True, 'resource_type': 'gpu', 'cluster_id': None, 'avail_vol_ask_id': 30409090, 'avail_vol_dph': 0.00024074074074074072, 'avail_vol_size': 581.0, 'nw_disk_min_bw': None, 'nw_disk_max_bw': None, 'nw_disk_avg_bw': None, 'rn': 1, 'dph_total_adj': 0.667967845775463, 'reliability2': 0.9981699, 'discount_rate': 0.0, 'discounted_hourly': 0.0, 'discounted_dph_total': 0.667962962962963, 'search': {'gpuCostPerHour': 0.6666666666666666, 'diskHour': 0.001296296296296296, 'totalHour': 0.667962962962963, 'discountTotalHour': 0, 'discountedTotalPerHour': 0.667962962962963}, 'instance': {'gpuCostPerHour': 0, 'diskHour': 0.001296296296296296, 'totalHour': 0.001296296296296296, 'discountTotalHour': 0, 'discountedTotalPerHour': 0.001296296296296296}, 'time_remaining': '', 'time_remaining_isbid': '', 'internet_up_cost_per_tb': 0.005333333333333333, 'internet_down_cost_per_tb': 0.004, 'datacenter': False}, {'id': 30753774, 'ask_contract_id': 30753774, 'bundle_id': 1618531469, 'bundled_results': None, 'bw_nvlink': 0.0, 'compute_cap': 1200, 'cpu_arch': 'amd64', 'cpu_cores': 192, 'cpu_cores_effective': 24.0, 'cpu_ghz': 2.4, 'cpu_name': 'AMD EPYC 9654 96-Core Processor', 'cpu_ram': 48299, 'credit_discount_max': 0.0, 'cuda_max_good': 13.0, 'direct_port_count': 374, 'disk_bw': 2535.600877642159, 'disk_name': 'Kingston DataTraveler', 'disk_space': 239.75, 'dlperf': 199.35716035702163, 'dlperf_per_dphtotal': 428.16237757145797, 'dph_base': 0.4653333333333334, 'dph_total': 0.46561111111111114, 'driver_version': '580.95.05', 'driver_vers': 580095005, 'duration': 15625252.28014493, 'end_date': 1789595337.0140142, 'external': None, 'flops_per_dphtotal': 234.41914807302228, 'geolocation': 'Ontario, CA', 'geolocode': 513588759, 'gpu_arch': 'nvidia', 'gpu_display_active': False, 'gpu_frac': 0.125, 'gpu_ids': [152548], 'gpu_lanes': 8, 'gpu_mem_bw': 1457.2, 'gpu_name': 'RTX 5090', 'gpu_ram': 32607, 'gpu_total_ram': 32607, 'gpu_max_power': 575.0, 'gpu_max_temp': 45.0, 'has_avx': 1, 'host_id': 208817, 'hosting_type': 0, 'hostname': None, 'inet_down': 7265.6, 'inet_down_cost': 0.007161458333333333, 'inet_up': 5573.4, 'inet_up_cost': 0.007161458333333333, 'is_bid': False, 'logo': '/static/logos/vastai_small2.png', 'machine_id': 46201, 'min_bid': 0.44, 'mobo_name': 'GENOAD24QM32-2L2T', 'num_gpus': 1, 'os_version': '22.04', 'pci_gen': 5.0, 'pcie_bw': 26.9, 'public_ipaddr': '74.14.5.197', 'reliability': 0.9947704, 'reliability_mult': 0.9502662, 'rentable': True, 'rented': False, 'score': 545.3923440071464, 'start_date': 1773967176.184, 'static_ip': False, 'storage_cost': 0.04000000000000001, 'storage_total_cost': 0.00027777777777777783, 'total_flops': 109.14815999999999, 'verification': 'verified', 'vericode': 1, 'vram_costperhour': 0.014613467455863262, 'webpage': None, 'vms_enabled': False, 'expected_reliability': 0.0, 'is_vm_deverified': True, 'resource_type': 'gpu', 'cluster_id': None, 'avail_vol_ask_id': 30753787, 'avail_vol_dph': 0.0005555555555555556, 'avail_vol_size': 959.0, 'nw_disk_min_bw': None, 'nw_disk_max_bw': None, 'nw_disk_avg_bw': None, 'rn': 1, 'dph_total_adj': 0.4745629340277778, 'reliability2': 0.9947704, 'discount_rate': 0.0, 'discounted_hourly': 0.0, 'discounted_dph_total': 0.46561111111111114, 'search': {'gpuCostPerHour': 0.4653333333333334, 'diskHour': 0.00027777777777777783, 'totalHour': 0.46561111111111114, 'discountTotalHour': 0, 'discountedTotalPerHour': 0.46561111111111114}, 'instance': {'gpuCostPerHour': 0, 'diskHour': 0.00027777777777777783, 'totalHour': 0.00027777777777777783, 'discountTotalHour': 0, 'discountedTotalPerHour': 0.00027777777777777783}, 'time_remaining': '', 'time_remaining_isbid': '', 'internet_up_cost_per_tb': 7.333333333333333, 'internet_down_cost_per_tb': 7.333333333333333, 'datacenter': False}, {'id': 31132142, 'ask_contract_id': 31132142, 'bundle_id': 1479187749, 'bundled_results': None, 'bw_nvlink': 0.0, 'compute_cap': 1200, 'cpu_arch': 'amd64', 'cpu_cores': 384, 'cpu_cores_effective': 96.0, 'cpu_ghz': 2.4, 'cpu_name': 'AMD EPYC 9654 96-Core Processor', 'cpu_ram': 386912, 'credit_discount_max': 0.0, 'cuda_max_good': 13.1, 'direct_port_count': 2499, 'disk_bw': 5652.883999999999, 'disk_name': 'KINGSTON SEDC3000ME7T6', 'disk_space': 748.0, 'dlperf': 564.0039214550288, 'dlperf_per_dphtotal': 297.94476436907837, 'dph_base': 1.8906666666666663, 'dph_total': 1.8929814814814812, 'driver_version': '590.48.01', 'driver_vers': 590048001, 'duration': 12060614.266130686, 'end_date': 1786030699.0, 'external': None, 'flops_per_dphtotal': 125.69844677708105, 'geolocation': 'Poland, PL', 'geolocode': 334059079, 'gpu_arch': 'nvidia', 'gpu_display_active': False, 'gpu_frac': 0.25, 'gpu_ids': [128347, 128346], 'gpu_lanes': 16, 'gpu_mem_bw': 1396.7, 'gpu_name': 'RTX PRO 6000 WS', 'gpu_ram': 97887, 'gpu_total_ram': 195774, 'gpu_max_power': 600.0, 'gpu_max_temp': 66.0, 'has_avx': 1, 'host_id': 66293, 'hosting_type': 0, 'hostname': None, 'inet_down': 5071.5, 'inet_down_cost': 0.005208333333333333, 'inet_up': 5023.1, 'inet_up_cost': 0.005208333333333333, 'is_bid': False, 'logo': '/static/logos/vastai_small2.png', 'machine_id': 37485, 'min_bid': 1.0666666666666667, 'mobo_name': 'TURIN2D24G-2L', 'num_gpus': 2, 'os_version': '24.04', 'pci_gen': 5.0, 'pcie_bw': 54.1, 'public_ipaddr': '140.150.159.2', 'reliability': 0.9885578, 'reliability_mult': 0.8972877, 'rentable': True, 'rented': False, 'score': 506.9599182872905, 'start_date': 1773968679.92, 'static_ip': False, 'storage_cost': 0.3333333333333333, 'storage_total_cost': 0.0023148148148148147, 'total_flops': 237.944832, 'verification': 'verified', 'vericode': 1, 'vram_costperhour': 0.009889171527713927, 'webpage': None, 'vms_enabled': False, 'expected_reliability': 0.0, 'is_vm_deverified': True, 'resource_type': 'gpu', 'cluster_id': None, 'avail_vol_ask_id': 31132156, 'avail_vol_dph': 0.00018518518518518515, 'avail_vol_size': 1483.0000000000007, 'nw_disk_min_bw': None, 'nw_disk_max_bw': None, 'nw_disk_avg_bw': None, 'rn': 1, 'dph_total_adj': 1.899491898148148, 'reliability2': 0.9885578, 'discount_rate': 0.0, 'discounted_hourly': 0.0, 'discounted_dph_total': 1.8929814814814812, 'search': {'gpuCostPerHour': 1.8906666666666663, 'diskHour': 0.0023148148148148147, 'totalHour': 1.8929814814814812, 'discountTotalHour': 0, 'discountedTotalPerHour': 1.8929814814814812}, 'instance': {'gpuCostPerHour': 0, 'diskHour': 0.0023148148148148147, 'totalHour': 0.0023148148148148147, 'discountTotalHour': 0, 'discountedTotalPerHour': 0.0023148148148148147}, 'time_remaining': '', 'time_remaining_isbid': '', 'internet_up_cost_per_tb': 5.333333333333333, 'internet_down_cost_per_tb': 5.333333333333333, 'datacenter': False}, {'id': 31929969, 'ask_contract_id': 31929969, 'bundle_id': 607005080, 'bundled_results': None, 'bw_nvlink': 0.0, 'compute_cap': 1000, 'cpu_arch': 'amd64', 'cpu_cores': 192, 'cpu_cores_effective': 24.0, 'cpu_ghz': 3.136083, 'cpu_name': 'Xeon® Platinum 8559C', 'cpu_ram': 255489, 'credit_discount_max': 0.0, 'cuda_max_good': 13.0, 'direct_port_count': 499, 'disk_bw': 41779.2, 'disk_name': 'Amazon EC2 NVMe Instance Storage', 'disk_space': 1484.3700302702832, 'dlperf': 676.1756492694622, 'dlperf_per_dphtotal': 216.2913876142223, 'dph_base': 3.125, 'dph_total': 3.1262254901960786, 'driver_version': '580.126.09', 'driver_vers': 580126009, 'duration': 1042357.2661306858, 'end_date': 1775012442.0, 'external': None, 'flops_per_dphtotal': 19.051708261858092, 'geolocation': 'Oregon, US', 'geolocode': 433199645, 'gpu_arch': 'nvidia', 'gpu_display_active': False, 'gpu_frac': 0.125, 'gpu_ids': [175353], 'gpu_lanes': 16, 'gpu_mem_bw': 6161.4, 'gpu_name': 'B200', 'gpu_ram': 183359, 'gpu_total_ram': 183359, 'gpu_max_power': 1000.0, 'gpu_max_temp': 58.0, 'has_avx': 1, 'host_id': 379418, 'hosting_type': 0, 'hostname': None, 'inet_down': 20154.2, 'inet_down_cost': 0.00011488970588235295, 'inet_up': 3640.9, 'inet_up_cost': 0.003446691176470588, 'is_bid': False, 'logo': '/static/logos/vastai_small2.png', 'machine_id': 56166, 'min_bid': 2.75, 'mobo_name': 'Not Specified', 'num_gpus': 1, 'os_version': '22.04', 'pci_gen': 5.0, 'pcie_bw': 50.3, 'public_ipaddr': '52.10.135.190', 'reliability': 0.9934648, 'reliability_mult': 0.9386096, 'rentable': True, 'rented': False, 'score': 505.36845052765204, 'start_date': 1773962642.667601, 'static_ip': True, 'storage_cost': 0.1764705882352941, 'storage_total_cost': 0.0012254901960784314, 'total_flops': 59.559936, 'verification': 'verified', 'vericode': 1, 'vram_costperhour': 0.016425507915522844, 'webpage': None, 'vms_enabled': False, 'expected_reliability': 0.0, 'is_vm_deverified': False, 'resource_type': 'gpu', 'cluster_id': None, 'avail_vol_ask_id': 31929970, 'avail_vol_dph': 0.00017361111111111112, 'avail_vol_size': 11874.960242162266, 'nw_disk_min_bw': None, 'nw_disk_max_bw': None, 'nw_disk_avg_bw': None, 'rn': 1, 'dph_total_adj': 3.1263691023284315, 'reliability2': 0.9934648, 'discount_rate': 0.0, 'discounted_hourly': 0.0, 'discounted_dph_total': 3.1262254901960786, 'search': {'gpuCostPerHour': 3.125, 'diskHour': 0.0012254901960784314, 'totalHour': 3.1262254901960786, 'discountTotalHour': 0, 'discountedTotalPerHour': 3.1262254901960786}, 'instance': {'gpuCostPerHour': 0, 'diskHour': 0.0012254901960784314, 'totalHour': 0.0012254901960784314, 'discountTotalHour': 0, 'discountedTotalPerHour': 0.0012254901960784314}, 'time_remaining': '', 'time_remaining_isbid': '', 'internet_up_cost_per_tb': 3.5294117647058822, 'internet_down_cost_per_tb': 0.11764705882352942, 'datacenter': False}, {'id': 31132145, 'ask_contract_id': 31132145, 'bundle_id': 1075535044, 'bundled_results': None, 'bw_nvlink': 0.0, 'compute_cap': 1200, 'cpu_arch': 'amd64', 'cpu_cores': 384, 'cpu_cores_effective': 48.0, 'cpu_ghz': 2.4, 'cpu_name': 'AMD EPYC 9654 96-Core Processor', 'cpu_ram': 193456, 'credit_discount_max': 0.0, 'cuda_max_good': 13.1, 'direct_port_count': 1249, 'disk_bw': 5652.883999999999, 'disk_name': 'KINGSTON SEDC3000ME7T6', 'disk_space': 374.0, 'dlperf': 282.0019607275144, 'dlperf_per_dphtotal': 297.58087036690796, 'dph_base': 0.9453333333333331, 'dph_total': 0.9476481481481479, 'driver_version': '590.48.01', 'driver_vers': 590048001, 'duration': 12060614.266130686, 'end_date': 1786030699.0, 'external': None, 'flops_per_dphtotal': 125.54492533171792, 'geolocation': 'Poland, PL', 'geolocode': 334059079, 'gpu_arch': 'nvidia', 'gpu_display_active': False, 'gpu_frac': 0.125, 'gpu_ids': [128347], 'gpu_lanes': 16, 'gpu_mem_bw': 1396.7, 'gpu_name': 'RTX PRO 6000 WS', 'gpu_ram': 97887, 'gpu_total_ram': 97887, 'gpu_max_power': 600.0, 'gpu_max_temp': 66.0, 'has_avx': 1, 'host_id': 66293, 'hosting_type': 0, 'hostname': None, 'inet_down': 5071.5, 'inet_down_cost': 0.005208333333333333, 'inet_up': 5023.1, 'inet_up_cost': 0.005208333333333333, 'is_bid': False, 'logo': '/static/logos/vastai_small2.png', 'machine_id': 37485, 'min_bid': 0.5333333333333333, 'mobo_name': 'TURIN2D24G-2L', 'num_gpus': 1, 'os_version': '24.04', 'pci_gen': 5.0, 'pcie_bw': 54.1, 'public_ipaddr': '140.150.159.2', 'reliability': 0.9885578, 'reliability_mult': 0.8972877, 'rentable': True, 'rented': False, 'score': 498.0491784478747, 'start_date': 1773968261.14, 'static_ip': False, 'storage_cost': 0.3333333333333333, 'storage_total_cost': 0.0023148148148148147, 'total_flops': 118.972416, 'verification': 'verified', 'vericode': 1, 'vram_costperhour': 0.009889171527713927, 'webpage': None, 'vms_enabled': False, 'expected_reliability': 0.0, 'is_vm_deverified': True, 'resource_type': 'gpu', 'cluster_id': None, 'avail_vol_ask_id': 31132156, 'avail_vol_dph': 0.00018518518518518515, 'avail_vol_size': 1483.0000000000007, 'nw_disk_min_bw': None, 'nw_disk_max_bw': None, 'nw_disk_avg_bw': None, 'rn': 1, 'dph_total_adj': 0.9541585648148145, 'reliability2': 0.9885578, 'discount_rate': 0.0, 'discounted_hourly': 0.0, 'discounted_dph_total': 0.9476481481481479, 'search': {'gpuCostPerHour': 0.9453333333333331, 'diskHour': 0.0023148148148148147, 'totalHour': 0.9476481481481479, 'discountTotalHour': 0, 'discountedTotalPerHour': 0.9476481481481479}, 'instance': {'gpuCostPerHour': 0, 'diskHour': 0.0023148148148148147, 'totalHour': 0.0023148148148148147, 'discountTotalHour': 0, 'discountedTotalPerHour': 0.0023148148148148147}, 'time_remaining': '', 'time_remaining_isbid': '', 'internet_up_cost_per_tb': 5.333333333333333, 'internet_down_cost_per_tb': 5.333333333333333, 'datacenter': False}, {'id': 28247754, 'ask_contract_id': 28247754, 'bundle_id': 2085611630, 'bundled_results': None, 'bw_nvlink': 0.0, 'compute_cap': 1200, 'cpu_arch': 'amd64', 'cpu_cores': 384, 'cpu_cores_effective': 96.0, 'cpu_ghz': 3.7093569000000004, 'cpu_name': 'AMD EPYC 9J14 96-Core Processor', 'cpu_ram': 193409, 'credit_discount_max': 0.05, 'cuda_max_good': 13.1, 'direct_port_count': 4749, 'disk_bw': 12390.4, 'disk_name': 'MEMBLAZE P7940DT0768Y00', 'disk_space': 1180.0, 'dlperf': 396.5355699810595, 'dlperf_per_dphtotal': 385.020601977474, 'dph_base': 1.0266666666666666, 'dph_total': 1.0299074074074073, 'driver_version': '590.48.01', 'driver_vers': 590048001, 'duration': 32545333.266130686, 'end_date': 1806515418.0, 'external': None, 'flops_per_dphtotal': 208.91478054481703, 'geolocation': 'Czechia, CZ', 'geolocode': 1924176688, 'gpu_arch': 'nvidia', 'gpu_display_active': False, 'gpu_frac': 0.25, 'gpu_ids': [138365, 138354], 'gpu_lanes': 16, 'gpu_mem_bw': 1452.7, 'gpu_name': 'RTX 5090', 'gpu_ram': 32607, 'gpu_total_ram': 65214, 'gpu_max_power': 575.0, 'gpu_max_temp': 63.0, 'has_avx': 1, 'host_id': 214845, 'hosting_type': 1, 'hostname': None, 'inet_down': 8659.5, 'inet_down_cost': 0.032552083333333336, 'inet_up': 3168.0, 'inet_up_cost': 0.020833333333333332, 'is_bid': False, 'logo': '/static/logos/vastai_small2.png', 'machine_id': 40773, 'min_bid': 0.5333333333333333, 'mobo_name': 'T1DMGEP', 'num_gpus': 2, 'os_version': '22.04', 'pci_gen': 5.0, 'pcie_bw': 54.1, 'public_ipaddr': '93.91.156.85', 'reliability': 0.9955449, 'reliability_mult': 0.9573191, 'rentable': True, 'rented': False, 'score': 475.9238736219089, 'start_date': 1773968583.812034, 'static_ip': False, 'storage_cost': 0.46666666666666673, 'storage_total_cost': 0.003240740740740741, 'total_flops': 215.16287999999997, 'verification': 'verified', 'vericode': 1, 'vram_costperhour': 0.016958321832735303, 'webpage': None, 'vms_enabled': False, 'expected_reliability': 0.0, 'is_vm_deverified': False, 'resource_type': 'gpu', 'cluster_id': None, 'avail_vol_ask_id': 28247759, 'avail_vol_dph': 0.0005555555555555556, 'avail_vol_size': 2068.0000000000005, 'nw_disk_min_bw': None, 'nw_disk_max_bw': None, 'nw_disk_avg_bw': None, 'rn': 1, 'dph_total_adj': 1.070597511574074, 'reliability2': 0.9955449, 'discount_rate': 0.0, 'discounted_hourly': 0.0, 'discounted_dph_total': 1.0299074074074073, 'search': {'gpuCostPerHour': 1.0266666666666666, 'diskHour': 0.003240740740740741, 'totalHour': 1.0299074074074073, 'discountTotalHour': 0, 'discountedTotalPerHour': 1.0299074074074073}, 'instance': {'gpuCostPerHour': 0, 'diskHour': 0.003240740740740741, 'totalHour': 0.003240740740740741, 'discountTotalHour': 0, 'discountedTotalPerHour': 0.003240740740740741}, 'time_remaining': '', 'time_remaining_isbid': '', 'internet_up_cost_per_tb': 21.333333333333332, 'internet_down_cost_per_tb': 33.333333333333336, 'datacenter': True}, {'id': 32293175, 'ask_contract_id': 32293175, 'bundle_id': 1785230567, 'bundled_results': None, 'bw_nvlink': 0.0, 'compute_cap': 1200, 'cpu_arch': 'amd64', 'cpu_cores': 128, 'cpu_cores_effective': 32.0, 'cpu_ghz': 2.45, 'cpu_name': 'AMD EPYC 7V12 64-Core Processor', 'cpu_ram': 24093, 'credit_discount_max': 0.0, 'cuda_max_good': 13.0, 'direct_port_count': 99, 'disk_bw': 2905.0, 'disk_name': 'SanDisk Ultra 3D NVMe 2TB', 'disk_space': 322.8003575470059, 'dlperf': 38.43516708680588, 'dlperf_per_dphtotal': 690.6818711106547, 'dph_base': 0.05333333333333334, 'dph_total': 0.055648148148148155, 'driver_version': '580.126.09', 'driver_vers': 580126009, 'duration': 13859169.266130686, 'end_date': 1787829254.0, 'external': None, 'flops_per_dphtotal': 413.3675021630616, 'geolocation': 'Guangdong, CN', 'geolocode': 921675020, 'gpu_arch': 'nvidia', 'gpu_display_active': False, 'gpu_frac': 0.25, 'gpu_ids': [169519], 'gpu_lanes': 8, 'gpu_mem_bw': 367.1, 'gpu_name': 'RTX 5060 Ti', 'gpu_ram': 16311, 'gpu_total_ram': 16311, 'gpu_max_power': 180.0, 'gpu_max_temp': 50.0, 'has_avx': 1, 'host_id': 115630, 'hosting_type': 0, 'hostname': None, 'inet_down': 1175.8, 'inet_down_cost': 0.0026041666666666665, 'inet_up': 789.0, 'inet_up_cost': 0.005208333333333333, 'is_bid': False, 'logo': '/static/logos/vastai_small2.png', 'machine_id': 53961, 'min_bid': 0.05333333333333334, 'mobo_name': 'H12SSL-i', 'num_gpus': 1, 'os_version': '22.04', 'pci_gen': 4.0, 'pcie_bw': 13.5, 'public_ipaddr': '1.193.136.196', 'reliability': 0.9927644, 'reliability_mult': 0.9324751, 'rentable': True, 'rented': False, 'score': 466.3082859371233, 'start_date': 1773968267.115, 'static_ip': False, 'storage_cost': 0.3333333333333333, 'storage_total_cost': 0.0023148148148148147, 'total_flops': 23.003136000000005, 'verification': 'verified', 'vericode': 1, 'vram_costperhour': 0.003348251691087814, 'webpage': None, 'vms_enabled': False, 'expected_reliability': 0.0, 'is_vm_deverified': False, 'resource_type': 'gpu', 'cluster_id': None, 'avail_vol_ask_id': 32293178, 'avail_vol_dph': 0.0004629629629629629, 'avail_vol_size': 671.0, 'nw_disk_min_bw': None, 'nw_disk_max_bw': None, 'nw_disk_avg_bw': None, 'rn': 1, 'dph_total_adj': 0.05890335648148149, 'reliability2': 0.9927644, 'discount_rate': 0.0, 'discounted_hourly': 0.0, 'discounted_dph_total': 0.055648148148148155, 'search': {'gpuCostPerHour': 0.05333333333333334, 'diskHour': 0.0023148148148148147, 'totalHour': 0.055648148148148155, 'discountTotalHour': 0, 'discountedTotalPerHour': 0.055648148148148155}, 'instance': {'gpuCostPerHour': 0, 'diskHour': 0.0023148148148148147, 'totalHour': 0.0023148148148148147, 'discountTotalHour': 0, 'discountedTotalPerHour': 0.0023148148148148147}, 'time_remaining': '', 'time_remaining_isbid': '', 'internet_u

In [41]:
import subprocess
import json

result = subprocess.run(["sky", "show-gpus", "--infra", "aws", "-a"], capture_output=True, text=True)
print(result.stdout)

⠋ Updating AWS catalog: aws/vms.csv (every 7 hours)
⠙ Updating AWS catalog: aws/vms.csv (every 7 hours)
⠹ Updating AWS catalog: aws/vms.csv (every 7 hours)
⠸ Updating AWS catalog: aws/vms.csv (every 7 hours)
⠼ Updating AWS catalog: aws/vms.csv (every 7 hours)
⠼ Updating AWS catalog: aws/vms.csv (every 7 hours)

COMMON_GPU  AVAILABLE_QUANTITIES
A10G        1, 4, 8
A100        8
A100-80GB   8
B200        8
H100        1, 8
H200        8
L4          0.125, 0.25, 0.5, 1, 4, 8
L40S        1, 4, 8
T4          1, 4, 8
V100        1, 4, 8
V100-32GB   8

OTHER_GPU        AVAILABLE_QUANTITIES
B300             8
Gaudi HL-205     8
Inferentia       1, 4, 16
Inferentia2      1, 6, 12
RTXPRO6000       1, 2, 4, 8
Radeon Pro V520  1, 2, 4
T4g              1, 2
Trainium         1, 16
Trainium2        16

GPU   QTY  CLOUD  INSTANCE_TYPE  DEVICE_MEM  vCPUs  HOST_MEM  HOURLY_PRICE  HOURLY_SPOT_PRICE
A100  8.0  AWS    p4d.24xlarge   40GB        96     1152GB    $ 21.958      $ 10.712

GPU        QTY  CLOUD  INSTANCE_TYPE  DEVICE_MEM  vCPUs  HOST_MEM  HOURLY_PRICE  HOURLY_SPOT_PRICE
A100-80GB  8.0  AWS    p4de.24xlarge  80GB        96     1152GB    $ 27.447      $ 15.109

GPU   QTY  CLOUD  INSTANCE_TYPE  DEVICE_MEM  vCPUs  HOST_MEM  HOURLY_PRICE  HOURLY_SPOT_PRICE
A10G  1.0  AWS    g5.xlarge      22GB        4      16GB      $ 1.006       $ 0.362
A10G  1.0  AWS    g5.2xlarge     22GB        8      32GB      $ 1.212       $ 0.307
A10G  1.0  AWS    g5.4xlarge     22GB        16     64GB      $ 1.624       $ 0.478
A10G  1.0  AWS    g5.8xlarge     22GB        32     128GB     $ 2.448       $ 0.656
A10G  1.0  AWS    g5.16xlarge    22GB        64     256GB     $ 4.096       $ 0.743
A10G  4.0  AWS    g5.12xlarge    22GB        48     192GB     $ 5.672       $ 1.715
A10G  4.0  AWS    g5.24xlarge    22GB        96     384GB     $ 8.144       $ 2.174
A10G  8.0  AWS    g5.48xlarge    22GB        192    768GB     $ 16.288      $ 3.613

GPU   QTY  CLOUD  INSTANCE_TYPE     DEVICE_MEM  vCPUs  HOST_MEM  HOURLY_PRICE  HOURLY_SPOT_PRICE
B200  8.0  AWS    p6-b200.48xlarge  179GB       192    2048GB    $ 113.933     $ 16.771

GPU   QTY  CLOUD  INSTANCE_TYPE     DEVICE_MEM  vCPUs  HOST_MEM  HOURLY_PRICE  HOURLY_SPOT_PRICE
B300  8.0  AWS    p6-b300.48xlarge  269GB       192    4096GB    $ 142.416     $ 17.871

GPU           QTY  CLOUD  INSTANCE_TYPE  DEVICE_MEM  vCPUs  HOST_MEM  HOURLY_PRICE  HOURLY_SPOT_PRICE
Gaudi HL-205  8.0  AWS    dl1.24xlarge   32GB        96     768GB     $ 13.109      $ 7.723

GPU   QTY  CLOUD  INSTANCE_TYPE  DEVICE_MEM  vCPUs  HOST_MEM  HOURLY_PRICE  HOURLY_SPOT_PRICE
H100  1.0  AWS    p5.4xlarge     80GB        16     256GB     $ 6.880       $ 2.634
H100  8.0  AWS    p5.48xlarge    80GB        192    2048GB    $ 55.040      $ 13.548

GPU   QTY  CLOUD  INSTANCE_TYPE  DEVICE_MEM  vCPUs  HOST_MEM  HOURLY_PRICE  HOURLY_SPOT_PRICE
H200  8.0  AWS    p5en.48xlarge  141GB       192    2048GB    $ 63.296      $ 10.655
H200  8.0  AWS    p5e.48xlarge   141GB       192    2048GB    -             $ 11.840

GPU         QTY   CLOUD  INSTANCE_TYPE  DEVICE_MEM  vCPUs  HOST_MEM  HOURLY_PRICE  HOURLY_SPOT_PRICE
Inferentia  1.0   AWS    inf1.xlarge    8GB         4      8GB       $ 0.228       $ 0.029
Inferentia  1.0   AWS    inf1.2xlarge   8GB         8      16GB      $ 0.362       $ 0.057
Inferentia  4.0   AWS    inf1.6xlarge   8GB         24     48GB      $ 1.180       $ 0.182
Inferentia  16.0  AWS    inf1.24xlarge  8GB         96     192GB     $ 4.721       $ 0.472

GPU          QTY   CLOUD  INSTANCE_TYPE  DEVICE_MEM  vCPUs  HOST_MEM  HOURLY_PRICE  HOURLY_SPOT_PRICE
Inferentia2  1.0   AWS    inf2.xlarge    32GB        4      16GB      $ 0.758       $ 0.076
Inferentia2  1.0   AWS    inf2.8xlarge   32GB        32     128GB     $ 1.968       $ 0.326
Inferentia2  6.0   AWS    inf2.24xlarge  32GB        96     384GB     $ 6.491       $ 0.649
Inferentia2  12.0  AWS    inf2.48xlarge  32GB        192    768GB     $ 12.981      $ 1.298

GPU  QTY    CLOUD  INSTANCE_TYPE  DEVICE_MEM  vCPUs  HOST_MEM  HOURLY_PRICE  HOURLY_SPOT_PRICE
L4   0.125  AWS    g6f.large      3GB         2      8GB       $ 0.202       $ 0.029
L4   0.125  AWS    g6f.xlarge     3GB         4      16GB      $ 0.237       $ 0.060
L4   0.25   AWS    g6f.2xlarge    6GB         8      32GB      $ 0.475       $ 0.103
L4   1.0    AWS    g6.xlarge      22GB        4      16GB      $ 0.805       $ 0.218
L4   0.5    AWS    g6f.4xlarge    11GB        16     64GB      $ 0.950       $ 0.264
L4   1.0    AWS    g6.2xlarge     22GB        8      32GB      $ 0.978       $ 0.260
L4   0.5    AWS    gr6f.4xlarge   11GB        16     128GB     $ 1.066       $ 0.298
L4   1.0    AWS    g6.4xlarge     22GB        16     64GB      $ 1.323       $ 0.456
L4   1.0    AWS    gr6.4xlarge    22GB        16     128GB     $ 1.539       $ 0.160
L4   1.0    AWS    g6.8xlarge     22GB        32     128GB     $ 2.014       $ 0.578
L4   1.0    AWS    gr6.8xlarge    22GB        32     256GB     $ 2.446       $ 0.271
L4   1.0    AWS    g6.16xlarge    22GB        64     256GB     $ 3.397       $ 0.848
L4   4.0    AWS    g6.12xlarge    22GB        48     192GB     $ 4.602       $ 1.208
L4   4.0    AWS    g6.24xlarge    22GB        96     384GB     $ 6.675       $ 1.797
L4   8.0    AWS    g6.48xlarge    22GB        192    768GB     $ 13.350      $ 3.628

GPU   QTY  CLOUD  INSTANCE_TYPE  DEVICE_MEM  vCPUs  HOST_MEM  HOURLY_PRICE  HOURLY_SPOT_PRICE
L40S  1.0  AWS    g6e.xlarge     45GB        4      32GB      $ 1.861       $ 0.615
L40S  1.0  AWS    g6e.2xlarge    45GB        8      64GB      $ 2.242       $ 0.583
L40S  1.0  AWS    g6e.4xlarge    45GB        16     128GB     $ 3.004       $ 0.668
L40S  1.0  AWS    g6e.8xlarge    45GB        32     256GB     $ 4.529       $ 0.964
L40S  1.0  AWS    g6e.16xlarge   45GB        64     512GB     $ 7.577       $ 0.972
L40S  4.0  AWS    g6e.12xlarge   45GB        48     384GB     $ 10.493      $ 3.327
L40S  4.0  AWS    g6e.24xlarge   45GB        96     768GB     $ 15.066      $ 4.047
L40S  8.0  AWS    g6e.48xlarge   45GB        192    1536GB    $ 30.131      $ 7.004

GPU         QTY  CLOUD  INSTANCE_TYPE  DEVICE_MEM  vCPUs  HOST_MEM  HOURLY_PRICE  HOURLY_SPOT_PRICE
RTXPRO6000  1.0  AWS    g7e.2xlarge    96GB        8      64GB      $ 3.363       $ 0.947
RTXPRO6000  1.0  AWS    g7e.4xlarge    96GB        16     128GB     $ 3.998       $ 0.879
RTXPRO6000  1.0  AWS    g7e.8xlarge    96GB        32     256GB     $ 5.268       $ 0.839
RTXPRO6000  2.0  AWS    g7e.12xlarge   96GB        48     512GB     $ 8.286       $ 0.882
RTXPRO6000  4.0  AWS    g7e.24xlarge   96GB        96     1024GB    $ 16.572      $ 1.657
RTXPRO6000  8.0  AWS    g7e.48xlarge   96GB        192    2048GB    $ 33.144      $ 4.204

GPU              QTY  CLOUD  INSTANCE_TYPE  DEVICE_MEM  vCPUs  HOST_MEM  HOURLY_PRICE  HOURLY_SPOT_PRICE
Radeon Pro V520  1.0  AWS    g4ad.xlarge    8GB         4      16GB      $ 0.379       $ 0.095
Radeon Pro V520  1.0  AWS    g4ad.2xlarge   8GB         8      32GB      $ 0.541       $ 0.130
Radeon Pro V520  1.0  AWS    g4ad.4xlarge   8GB         16     64GB      $ 0.867       $ 0.215
Radeon Pro V520  2.0  AWS    g4ad.8xlarge   8GB         32     128GB     $ 1.734       $ 0.199
Radeon Pro V520  4.0  AWS    g4ad.16xlarge  8GB         64     256GB     $ 3.468       $ 0.618

GPU  QTY  CLOUD  INSTANCE_TYPE  DEVICE_MEM  vCPUs  HOST_MEM  HOURLY_PRICE  HOURLY_SPOT_PRICE
T4   1.0  AWS    g4dn.xlarge    16GB        4      16GB      $ 0.526       $ 0.158
T4   1.0  AWS    g4dn.2xlarge   16GB        8      32GB      $ 0.752       $ 0.209
T4   1.0  AWS    g4dn.4xlarge   16GB        16     64GB      $ 1.204       $ 0.362
T4   1.0  AWS    g4dn.8xlarge   16GB        32     128GB     $ 2.176       $ 0.617
T4   4.0  AWS    g4dn.12xlarge  16GB        48     192GB     $ 3.912       $ 1.034
T4   1.0  AWS    g4dn.16xlarge  16GB        64     256GB     $ 4.352       $ 0.925
T4   8.0  AWS    g4dn.metal     16GB        96     384GB     $ 7.824       $ 2.747

GPU  QTY  CLOUD  INSTANCE_TYPE  DEVICE_MEM  vCPUs  HOST_MEM  HOURLY_PRICE  HOURLY_SPOT_PRICE
T4g  1.0  AWS    g5g.xlarge     16GB        4      8GB       $ 0.420       $ 0.120
T4g  1.0  AWS    g5g.2xlarge    16GB        8      16GB      $ 0.556       $ 0.124
T4g  1.0  AWS    g5g.4xlarge    16GB        16     32GB      $ 0.828       $ 0.230
T4g  1.0  AWS    g5g.8xlarge    16GB        32     64GB      $ 1.372       $ 0.232
T4g  2.0  AWS    g5g.metal      16GB        64     128GB     $ 2.744       $ 0.344
T4g  2.0  AWS    g5g.16xlarge   16GB        64     128GB     $ 2.744       $ 0.355

GPU       QTY   CLOUD  INSTANCE_TYPE   DEVICE_MEM  vCPUs  HOST_MEM  HOURLY_PRICE  HOURLY_SPOT_PRICE
Trainium  1.0   AWS    trn1.2xlarge    32GB        8      32GB      $ 1.344       $ 0.171
Trainium  16.0  AWS    trn1.32xlarge   32GB        128    512GB     $ 21.500      $ 2.150
Trainium  16.0  AWS    trn1n.32xlarge  32GB        128    512GB     $ 24.780      $ 2.478

GPU        QTY   CLOUD  INSTANCE_TYPE  DEVICE_MEM  vCPUs  HOST_MEM  HOURLY_PRICE  HOURLY_SPOT_PRICE
Trainium2  16.0  AWS    trn2.48xlarge  512GB       192    2048GB    -             $ 8.596

GPU   QTY  CLOUD  INSTANCE_TYPE  DEVICE_MEM  vCPUs  HOST_MEM  HOURLY_PRICE  HOURLY_SPOT_PRICE
V100  1.0  AWS    p3.2xlarge     16GB        8      61GB      $ 3.060       $ 0.400
V100  4.0  AWS    p3.8xlarge     16GB        32     244GB     $ 12.240      $ 1.378
V100  8.0  AWS    p3.16xlarge    16GB        64     488GB     $ 24.480      $ 2.987

GPU        QTY  CLOUD  INSTANCE_TYPE  DEVICE_MEM  vCPUs  HOST_MEM  HOURLY_PRICE  HOURLY_SPOT_PRICE
V100-32GB  8.0  AWS    p3dn.24xlarge  32GB        96     768GB     $ 31.212      $ 4.510

In [36]:
import re
import pandas as pd

text = result.stdout


# =========================
# HELPERS
# =========================

def parse_quantities(q_str):
    """Parsea cantidades (int + float) de forma robusta."""
    values = []
    for x in q_str.split(","):
        x = x.strip()
        try:
            val = float(x)
            if val.is_integer():
                val = int(val)
            values.append(val)
        except:
            continue
    return values


def parse_qty(x):
    """Parsea qty individual (puede ser float tipo 0.5)."""
    try:
        val = float(x)
        return int(val) if val.is_integer() else val
    except:
        return None


# =========================
# COMMON_GPU
# =========================

common_pattern = re.search(
    r"COMMON_GPU\s+AVAILABLE_QUANTITIES\s+(.*?)\n\n",
    text,
    re.DOTALL
)

common_rows = []
if common_pattern:
    for row in common_pattern.group(1).strip().split("\n"):
        m = re.match(r"(\S+)\s+(.+)", row.strip())
        if m:
            common_rows.append({
                "gpu": m.group(1),
                "quantities": parse_quantities(m.group(2))
            })

df_common = pd.DataFrame(common_rows)


# =========================
# OTHER_GPU
# =========================

other_pattern = re.search(
    r"OTHER_GPU\s+AVAILABLE_QUANTITIES\s+(.*?)\n\nGPU\s+QTY",
    text,
    re.DOTALL
)

other_rows = []
if other_pattern:
    for row in other_pattern.group(1).strip().split("\n"):
        m = re.match(r"(\S+)\s+(.+)", row.strip())
        if m:
            other_rows.append({
                "gpu": m.group(1),
                "quantities": parse_quantities(m.group(2))
            })

df_other = pd.DataFrame(other_rows)


# =========================
# PRICING
# =========================

pricing_blocks = re.findall(
    r"GPU\s+QTY\s+CLOUD.*?\n(.*?)(?=\nGPU\s+QTY|\Z)",
    text,
    re.DOTALL
)

rows = []

row_pattern = re.compile(
    r"(\S+)\s+"          # GPU
    r"([\d.]+)\s+"       # QTY
    r"(\S+)\s+"          # CLOUD
    r"(\S+)\s+"          # INSTANCE TYPE
    r"(\S+)\s+"          # DEVICE MEM
    r"(\d+)\s+"          # VCPUS
    r"(\S+)\s+"          # HOST MEM
    r"\$\s*([\d.]+)\s+"  # PRICE
    r"\$\s*([\d.]+)"     # SPOT PRICE
)

for block in pricing_blocks:
    for line in block.strip().split("\n"):
        m = row_pattern.match(line.strip())
        if m:
            rows.append({
                "gpu": m.group(1),
                "qty": parse_qty(m.group(2)),
                "cloud": m.group(3),
                "instance_type": m.group(4),
                "device_mem": m.group(5),
                "vcpus": int(m.group(6)),
                "host_mem": m.group(7),
                "price": float(m.group(8)),
                "spot_price": float(m.group(9)),
            })

df_pricing = pd.DataFrame(rows)


# =========================
# OPTIONAL: EXPLODE QUANTITIES
# =========================

df_common_expanded = df_common.explode("quantities")
df_other_expanded = df_other.explode("quantities")


# =========================
# OPTIONAL: NORMALIZE PRICE PER GPU
# =========================

def safe_divide(price, qty):
    try:
        return price / qty if qty else None
    except:
        return None

df_pricing["price_per_gpu"] = df_pricing.apply(
    lambda x: safe_divide(x["price"], x["qty"]),
    axis=1
)

df_pricing["spot_price_per_gpu"] = df_pricing.apply(
    lambda x: safe_divide(x["spot_price"], x["qty"]),
    axis=1
)


# =========================
# OUTPUT
# =========================

print("\n=== COMMON GPU ===")
print(df_common)

print("\n=== OTHER GPU ===")
print(df_other)

print("\n=== PRICING ===")
print(df_pricing.head())

print("\n=== COMMON EXPANDED ===")
print(df_common_expanded.head())

=== COMMON GPU ===
          gpu                   quantities
0        A10G                    [1, 4, 8]
1        A100                          [8]
2   A100-80GB                          [8]
3        B200                          [8]
4        H100                       [1, 8]
5        H200                          [8]
6          L4  [0.125, 0.25, 0.5, 1, 4, 8]
7        L40S                    [1, 4, 8]
8          T4                    [1, 4, 8]
9        V100                    [1, 4, 8]
10  V100-32GB                          [8]

=== OTHER GPU ===
           gpu    quantities
0         B300           [8]
1        Gaudi            []
2   Inferentia    [1, 4, 16]
3  Inferentia2    [1, 6, 12]
4   RTXPRO6000  [1, 2, 4, 8]
5       Radeon        [2, 4]
6          T4g        [1, 2]
7     Trainium       [1, 16]
8    Trainium2          [16]

=== PRICING ===
         gpu  qty cloud  instance_type device_mem  vcpus host_mem   price  \
0       A100  8.0   AWS   p4d.24xlarge       40GB     96   1152GB  21.958
1  A100-80GB  8.0   AWS  p4de.24xlarge       80GB     96   1152GB  27.447
2       A10G  1.0   AWS      g5.xlarge       22GB      4     16GB   1.006
3       A10G  1.0   AWS     g5.2xlarge       22GB      8     32GB   1.212
4       A10G  1.0   AWS     g5.4xlarge       22GB     16     64GB   1.624

   spot_price  price_per_gpu  spot_price_per_gpu
0      10.712       2.744750            1.339000
1      15.109       3.430875            1.888625
2       0.362       1.006000            0.362000
3       0.307       1.212000            0.307000
4       0.478       1.624000            0.478000

=== COMMON EXPANDED ===
         gpu quantities
0       A10G          1
0       A10G          4
0       A10G          8
1       A100          8
2  A100-80GB          8

In [37]:
df_other

           gpu    quantities
0         B300           [8]
1        Gaudi            []
2   Inferentia    [1, 4, 16]
3  Inferentia2    [1, 6, 12]
4   RTXPRO6000  [1, 2, 4, 8]
5       Radeon        [2, 4]
6          T4g        [1, 2]
7     Trainium       [1, 16]
8    Trainium2          [16]

In [30]:
import requests
import os

API_KEY = os.getenv("RUNPOD_API_KEY")
url = f"https://api.runpod.io/graphql?api_key={API_KEY}"

def run_query(query):
    response = requests.post(
        url,
        json={"query": query},
        headers={"Content-Type": "application/json"}
    )
    return response.json()["data"]

# -------- GPUs --------
gpus = run_query("""
query {
  gpuTypes {
    id
    displayName
  }
}
""")["gpuTypes"]

# -------- REGIONS --------
regions = run_query("""
query {
  dataCenters {
    id
    name
    location
  }
}
""")["dataCenters"]

print("GPUs:", len(gpus))
print("Regions:", len(regions))

GPUs: 43
Regions: 44

In [39]:
import boto3
import pandas as pd

def find_instance_globally(instance_type):
    # Cliente inicial para obtener la lista de todas las regiones activas
    ec2_global = boto3.client('ec2', region_name='us-east-1')
    regions = [r['RegionName'] for r in ec2_global.describe_regions()['Regions']]
    
    results = []

    print(f"Buscando {instance_type} en todas las regiones...")

    for region in regions:
        try:
            ec2_regional = boto3.client('ec2', region_name=region)
            
            # Consultamos si el tipo de instancia existe en esa región y en qué zonas
            response = ec2_regional.describe_instance_type_offerings(
                LocationType='availability-zone',
                Filters=[{'Name': 'instance-type', 'Values': [instance_type]}]
            )
            
            offerings = response['InstanceTypeOfferings']
            
            if offerings:
                for o in offerings:
                    results.append({
                        'Region': region,
                        'AvailabilityZone': o['Location'],
                        'InstanceType': o['InstanceType'],
                        'Status': 'Físicamente Disponible'
                    })
            else:
                # Si quieres registrar que NO está en la región, descomenta esto:
                # results.append({'Region': region, 'AvailabilityZone': 'N/A', 'Status': 'No ofrecida'})
                pass
                
        except Exception as e:
            print(f"No se pudo consultar la región {region}: {e}")

    return pd.DataFrame(results)

# --- EJECUCIÓN ---
# Cambia 'g5.2xlarge' por la GPU que necesites (ej. 'p4d.24xlarge', 'g4dn.xlarge')
mi_gpu = 'g5.2xlarge'
df_disponibilidad = find_instance_globally(mi_gpu)

# Mostrar resultados ordenados por Región
print(df_disponibilidad.sort_values(by='Region'))

Buscando g5.2xlarge en todas las regiones...
            Region AvailabilityZone InstanceType                  Status
13  ap-northeast-1  ap-northeast-1c   g5.2xlarge  Físicamente Disponible
12  ap-northeast-1  ap-northeast-1a   g5.2xlarge  Físicamente Disponible
10  ap-northeast-2  ap-northeast-2d   g5.2xlarge  Físicamente Disponible
11  ap-northeast-2  ap-northeast-2a   g5.2xlarge  Físicamente Disponible
9   ap-northeast-2  ap-northeast-2c   g5.2xlarge  Físicamente Disponible
0       ap-south-1      ap-south-1a   g5.2xlarge  Físicamente Disponible
1       ap-south-1      ap-south-1b   g5.2xlarge  Físicamente Disponible
19  ap-southeast-2  ap-southeast-2a   g5.2xlarge  Físicamente Disponible
18  ap-southeast-2  ap-southeast-2c   g5.2xlarge  Físicamente Disponible
14    ca-central-1    ca-central-1b   g5.2xlarge  Físicamente Disponible
15    ca-central-1    ca-central-1a   g5.2xlarge  Físicamente Disponible
22    eu-central-1    eu-central-1b   g5.2xlarge  Físicamente Disponible
21    eu-central-1    eu-central-1c   g5.2xlarge  Físicamente Disponible
20    eu-central-1    eu-central-1a   g5.2xlarge  Físicamente Disponible
3       eu-north-1      eu-north-1b   g5.2xlarge  Físicamente Disponible
2       eu-north-1      eu-north-1c   g5.2xlarge  Físicamente Disponible
6        eu-west-1       eu-west-1b   g5.2xlarge  Físicamente Disponible
7        eu-west-1       eu-west-1c   g5.2xlarge  Físicamente Disponible
8        eu-west-1       eu-west-1a   g5.2xlarge  Físicamente Disponible
4        eu-west-2       eu-west-2a   g5.2xlarge  Físicamente Disponible
5        eu-west-2       eu-west-2b   g5.2xlarge  Físicamente Disponible
16       sa-east-1       sa-east-1a   g5.2xlarge  Físicamente Disponible
17       sa-east-1       sa-east-1b   g5.2xlarge  Físicamente Disponible
23       us-east-1       us-east-1a   g5.2xlarge  Físicamente Disponible
24       us-east-1       us-east-1c   g5.2xlarge  Físicamente Disponible
25       us-east-1       us-east-1b   g5.2xlarge  Físicamente Disponible
26       us-east-1       us-east-1d   g5.2xlarge  Físicamente Disponible
27       us-east-1       us-east-1f   g5.2xlarge  Físicamente Disponible
28       us-east-2       us-east-2b   g5.2xlarge  Físicamente Disponible
29       us-east-2       us-east-2c   g5.2xlarge  Físicamente Disponible
30       us-east-2       us-east-2a   g5.2xlarge  Físicamente Disponible
32       us-west-2       us-west-2c   g5.2xlarge  Físicamente Disponible
31       us-west-2       us-west-2b   g5.2xlarge  Físicamente Disponible
33       us-west-2       us-west-2a   g5.2xlarge  Físicamente Disponible

In [49]:
import requests
import os
import pandas as pd

API_KEY = os.getenv("RUNPOD_API_KEY")
url = f"https://api.runpod.io/graphql?api_key={API_KEY}"

def run_query(query):
    response = requests.post(
        url,
        json={"query": query},
        headers={"Content-Type": "application/json"}
    )
    return response.json()["data"]

# -------- INPUT --------
GPU_ID = "NVIDIA RTX 2000 Ada Generation"

print(f"Buscando {GPU_ID} en todas las regiones...")

# -------- REGIONS --------
regions = run_query("""
query {
  dataCenters {
    id
    name
    location
  }
}
""")["dataCenters"]

results = []

# -------- LOOP POR REGION --------
for region in regions:
    region_id = region["id"]
    region_name = region["name"]

    query = f"""
    query {{
      gpuTypes(input: {{ id: "{GPU_ID}" }}) {{
        id
        displayName
        lowestPrice(
          input: {{
            secureCloud: true,
            gpuCount: 1,
            minVcpuCount: 2,
            minMemoryInGb: 8,
            minDisk: 0,
            dataCenterId: "{region_id}",
            globalNetwork: false,
            compliance: null
          }}
        ) {{
          stockStatus
          availableGpuCounts
          maxUnreservedGpuCount
        }}
      }}
    }}
    """

    try:
        data = run_query(query)["gpuTypes"][0]["lowestPrice"]

        status = data["stockStatus"]

        # 🚨 FILTRO AQUÍ
        if status is None:
            continue

        if status == "AVAILABLE":
            status_readable = "Físicamente Disponible"
        elif status == "OUT_OF_STOCK":
            status_readable = "Sin stock"
        else:
            status_readable = status

        results.append({
            "Region": region_name,
            "GPU": GPU_ID,
            "AvailableCounts": data["availableGpuCounts"],
            "MaxAvailable": data["maxUnreservedGpuCount"],
            "Status": status_readable
        })

    except Exception as e:
        # Algunas regiones no tienen ese GPU
        results.append({
            "Region": region_name,
            "GPU": GPU_ID,
            "AvailableCounts": None,
            "MaxAvailable": 0,
            "Status": "No disponible"
        })

# -------- DATAFRAME --------
df = pd.DataFrame(results)

# opcional: ordenar por disponibilidad
df = df.sort_values(by="MaxAvailable", ascending=False)

print(df)

Buscando NVIDIA RTX 2000 Ada Generation en todas las regiones...
     Region                             GPU AvailableCounts  MaxAvailable  \
0   EU-RO-1  NVIDIA RTX 2000 Ada Generation          [1, 2]             2
1  EUR-IS-1  NVIDIA RTX 2000 Ada Generation             [1]             1

  Status
0    Low
1    Low

In [48]:
df

,Region,RegionID,GPU,AvailableCounts,MaxAvailable,Status
9,EU-RO-1,EU-RO-1,NVIDIA RTX 2000 Ada Generation,[1],1,Low
12,EUR-IS-1,EUR-IS-1,NVIDIA RTX 2000 Ada Generation,[1],1,Low
2,CA-MTL-2,CA-MTL-2,NVIDIA RTX 2000 Ada Generation,[],0,None
0,AP-JP-1,AP-JP-1,NVIDIA RTX 2000 Ada Generation,[],0,None
3,CA-MTL-3,CA-MTL-3,NVIDIA RTX 2000 Ada Generation,[],0,None
4,CA-MTL-4,CA-MTL-4,NVIDIA RTX 2000 Ada Generation,[],0,None
6,EU-DK-1,EU-DK-1,NVIDIA RTX 2000 Ada Generation,[],0,None
5,EU-CZ-1,EU-CZ-1,NVIDIA RTX 2000 Ada Generation,[],0,None
7,EU-FR-1,EU-FR-1,NVIDIA RTX 2000 Ada Generation,[],0,None
8,EU-NL-1,EU-NL-1,NVIDIA RTX 2000 Ada Generation,[],0,None
10,EU-SE-1,EU-SE-1,NVIDIA RTX 2000 Ada Generation,[],0,None
1,CA-MTL-1,CA-MTL-1,NVIDIA RTX 2000 Ada Generation,[],0,None
11,EU-SE-2,EU-SE-2,NVIDIA RTX 2000 Ada Generation,[],0,None
13,EUR-IS-2,EUR-IS-2,NVIDIA RTX 2000 Ada Generation,[],0,None
14,EUR-IS-3,EUR-IS-3,NVIDIA RTX 2000 Ada Generation,[],0,None
15,EUR-IS-4,EUR-IS-4,NVIDIA RTX 2000 Ada Generation,[],0,None
16,EUR-NO-1,EUR-NO-1,NVIDIA RTX 2000 Ada Generation,[],0,None
17,EUR-NO-2,EUR-NO-2,NVIDIA RTX 2000 Ada Generation,[],0,None
18,OC-AU-1,OC-AU-1,NVIDIA RTX 2000 Ada Generation,[],0,None
19,SEA-SG-1,SEA-SG-1,NVIDIA RTX 2000 Ada Generation,[],0,None
20,US-CA-1,US-CA-1,NVIDIA RTX 2000 Ada Generation,[],0,None
21,US-CA-2,US-CA-2,NVIDIA RTX 2000 Ada Generation,[],0,None
22,US-DE-1,US-DE-1,NVIDIA RTX 2000 Ada Generation,[],0,None
23,US-GA-1,US-GA-1,NVIDIA RTX 2000 Ada Generation,[],0,None
24,US-GA-2,US-GA-2,NVIDIA RTX 2000 Ada Generation,[],0,None
25,US-IL-1,US-IL-1,NVIDIA RTX 2000 Ada Generation,[],0,None
26,US-KS-1,US-KS-1,NVIDIA RTX 2000 Ada Generation,[],0,None
27,US-KS-2,US-KS-2,NVIDIA RTX 2000 Ada Generation,[],0,None
28,US-KS-3,US-KS-3,NVIDIA RTX 2000 Ada Generation,[],0,None
29,US-MD-1,US-MD-1,NVIDIA RTX 2000 Ada Generation,[],0,None
30,US-MO-1,US-MO-1,NVIDIA RTX 2000 Ada Generation,[],0,None
31,US-MO-2,US-MO-2,NVIDIA RTX 2000 Ada Generation,[],0,None
32,US-NC-1,US-NC-1,NVIDIA RTX 2000 Ada Generation,[],0,None
33,US-NC-2,US-NC-2,NVIDIA RTX 2000 Ada Generation,[],0,None
34,US-NE-1,US-NE-1,NVIDIA RTX 2000 Ada Generation,[],0,None
35,US-OR-1,US-OR-1,NVIDIA RTX 2000 Ada Generation,[],0,None
36,US-OR-2,US-OR-2,NVIDIA RTX 2000 Ada Generation,[],0,None
37,US-PA-1,US-PA-1,NVIDIA RTX 2000 Ada Generation,[],0,None
38,US-TX-1,US-TX-1,NVIDIA RTX 2000 Ada Generation,[],0,None
39,US-TX-2,US-TX-2,NVIDIA RTX 2000 Ada Generation,[],0,None
40,US-TX-3,US-TX-3,NVIDIA RTX 2000 Ada Generation,[],0,None
41,US-TX-4,US-TX-4,NVIDIA RTX 2000 Ada Generation,[],0,None
42,US-TX-5,US-TX-5,NVIDIA RTX 2000 Ada Generation,[],0,None
43,US-WA-1,US-WA-1,NVIDIA RTX 2000 Ada Generation,[],0,None

In [62]:
import pandas as pd
from vastai_sdk import VastAI
import os

vast_sdk = VastAI(api_key=os.getenv("VAST_AI_KEY"))

def get_vast_exact(gpu_id="RTX 4090"):
    # IMPORTANTE: Cambiamos ~ por = y ponemos el ID entre comillas dobles
    # Esto obliga a que el nombre sea exactamente el que pides.
    query = f'gpu_name = "{gpu_id}" rentable = True'
    
    try:
        offers = vast_sdk.search_offers(query=query)
        if not offers:
            print(f"No se encontraron ofertas exactas para: {gpu_id}")
            return None

        df = pd.DataFrame(offers)

        # Mapeo de columnas (mantenemos la lógica flexible por seguridad)
        price_col = next((c for c in ['dph_total', 'rentable_price', 'price'] if c in df.columns), None)
        loc_col = next((c for c in ['geolocation', 'geolocation_caption', 'location'] if c in df.columns), None)
        gpu_col = next((c for c in ['num_gpus', 'gpu_count'] if c in df.columns), None)

        if not price_col or not gpu_col or not loc_col:
            print("Error: No se identificaron las columnas necesarias.")
            return None

        # Asegurar tipos numéricos
        df[gpu_col] = pd.to_numeric(df[gpu_col], errors='coerce').fillna(0)
        df[price_col] = pd.to_numeric(df[price_col], errors='coerce').fillna(0)

        # Agrupación por Región
        summary = df.groupby(loc_col).agg({
            'id': 'count',
            gpu_col: 'sum',
            price_col: 'min'
        }).rename(columns={
            'id': 'Hosts',
            gpu_col: 'Total_GPUs',
            price_col: 'Precio_Min_Hr'
        })

        return summary.sort_values(by='Total_GPUs', ascending=False)

    except Exception as e:
        print(f"Error detallado: {e}")
        return None

# Ejecución con ID exacto
# Nota: "RTX 4090" es el standard de Vast, pero asegúrate de que sea el ID correcto
df_vast = get_vast_exact("RTX 4090")

if df_vast is not None:
    print(f"Resultados exactos para RTX 4090:")
    print(df_vast)

Resultados exactos para RTX 4090:
                      Hosts  Total_GPUs  Precio_Min_Hr
geolocation
Iceland, IS               8          11       0.348056
Texas, US                 8          11       0.375185
Japan, JP                 3          10       1.000926
The Netherlands, NL       6           8       0.308056
Spain, ES                 5           6       0.277852
Hungary, HU               5           6       0.301852
United Kingdom, GB        5           6       0.375472
France, FR                4           5       0.268056
Bulgaria, BG              2           4       0.534722
Washington, US            3           4       0.547185
Illinois, US              2           3       0.354583
Quebec, CA                2           3       0.308056
Utah, US                  2           3       0.427593
Sweden, SE                2           2       0.328981
Nebraska, US              1           2       0.720463
British Columbia, CA      1           2       0.612056
Georgia, US               1           2       0.534722
Finland, FI               1           1       0.402315
Brazil, BR                1           1       0.294722
South Korea, KR           1           1       0.268056
Thailand, TH              1           1       0.293389

In [63]:
import pandas as pd
from vastai_sdk import VastAI
import os

vast_sdk = VastAI(api_key=os.getenv("VAST_AI_KEY"))

def get_vast_gpu_catalog():
    try:
        # Consultamos todas las ofertas de alquiler disponibles en el marketplace
        # Sin filtros de nombre para traer todo el inventario
        offers = vast_sdk.search_offers(query="rentable = True")
        
        if not offers:
            print("No se pudieron recuperar ofertas.")
            return None

        df = pd.DataFrame(offers)

        # Buscamos la columna de nombre de GPU (usualmente 'gpu_name')
        gpu_col = next((c for c in ['gpu_name', 'model', 'gpu_model'] if c in df.columns), None)
        
        if not gpu_col:
            print("No se encontró la columna de nombre de GPU.")
            return None

        # Obtenemos la lista única de modelos, ordenada alfabéticamente
        gpu_list = sorted(df[gpu_col].unique())
        
        # Opcional: Contar cuántas unidades hay de cada una en todo el marketplace
        catalog_summary = df.groupby(gpu_col).agg({
            'id': 'count',
            'num_gpus': 'sum'
        }).rename(columns={'id': 'Total_Hosts', 'num_gpus': 'Total_Units'}).sort_values('Total_Units', ascending=False)

        return catalog_summary

    except Exception as e:
        print(f"Error al obtener el catálogo: {e}")
        return None

# Ejecución
catalogo_gpus = get_vast_gpu_catalog()

if catalogo_gpus is not None:
    print("Catálogo de GPUs disponibles en Vast.ai (IDs exactos):")
    print(catalogo_gpus)
    
    # Si solo quieres ver los nombres para copiar y pegar:
    print("\nLista de IDs para búsqueda exacta:")
    print(list(catalogo_gpus.index))

Catálogo de GPUs disponibles en Vast.ai (IDs exactos):
                 Total_Hosts  Total_Units
gpu_name
RTX 5090                   7           22
H200                       5           16
RTX PRO 6000 S             5           10
RTX 4070S Ti               3            7
RTX 4070 Ti                3            7
RTX 5080                   3            7
RTX 4090                   4            7
RTX PRO 4000               4            6
H100 NVL                   3            5
RTX 5060 Ti                3            5
RTX PRO 5000               3            4
RTX PRO 6000 WS            3            4
RTX 6000Ada                2            3
RTX 5070 Ti                2            3
RTX 5070                   2            3
RTX 4070                   2            3
H200 NVL                   2            2
RTX 3090                   1            1
L40                        1            1
B200                       1            1
H100 SXM                   1            1
A100X                      1            1
RTX 4080S                  1            1
RTX 4070S                  1            1
RTX 4080                   1            1

Lista de IDs para búsqueda exacta:
['RTX 5090', 'H200', 'RTX PRO 6000 S', 'RTX 4070S Ti', 'RTX 4070 Ti', 'RTX 5080', 'RTX 4090', 'RTX PRO 4000', 'H100 NVL', 'RTX 5060 Ti', 'RTX PRO 5000', 'RTX PRO 6000 WS', 'RTX 6000Ada', 'RTX 5070 Ti', 'RTX 5070', 'RTX 4070', 'H200 NVL', 'RTX 3090', 'L40', 'B200', 'H100 SXM', 'A100X', 'RTX 4080S', 'RTX 4070S', 'RTX 4080']

In [65]:
import pandas as pd
from vastai_sdk import VastAI
import os

vast_sdk = VastAI(api_key=os.getenv("VAST_AI_KEY"))

def get_vast_human_readable(gpu_id="RTX 4090"):
    query = f'gpu_name = "{gpu_id}" rentable = True'
    
    try:
        offers = vast_sdk.search_offers(query=query)
        if not offers:
            print(f"No se encontraron ofertas para: {gpu_id}")
            return None

        df = pd.DataFrame(offers)

        # 1. Conversiones de Unidades
        # Red: Mbps -> MB/s (Megabytes por segundo)
        df['MBs_Down'] = (pd.to_numeric(df['inet_down']) / 8).round(1)
        df['MBs_Up'] = (pd.to_numeric(df['inet_up']) / 8).round(1)
        
        # Costos: $/GB -> $/TB
        df['Egress_$/TB'] = (pd.to_numeric(df['inet_up_cost']) * 1024).round(2)
        df['Ingress_$/TB'] = (pd.to_numeric(df['inet_down_cost']) * 1024).round(2)
        
        # VRAM: MB -> GB
        df['VRAM_GB'] = (pd.to_numeric(df['gpu_ram']) / 1024).astype(int)
        
        # Confiabilidad: 0.99 -> 99%
        df['Reliability_%'] = (pd.to_numeric(df['reliability2']) * 100).round(1)

        # 2. Selección de columnas con nombres entendibles
        cols_map = {
            'id': 'Offer_ID',
            'geolocation': 'Region',
            'num_gpus': 'GPUs',
            'VRAM_GB': 'VRAM_GB',
            'dph_total': 'Price_$/Hr',
            'MBs_Down': 'Descarga_MB/s',
            'MBs_Up': 'Subida_MB/s',
            'Egress_$/TB': 'Costo_Egress_$/TB',
            'Ingress_$/TB': 'Costo_Ingress_$/TB',
            'Reliability_%': 'Reliability_%'
        }

        df_final = df[list(cols_map.keys())].rename(columns=cols_map)

        # Ordenar por el más barato
        return df_final.sort_values(by='Price_$/Hr', ascending=True)

    except Exception as e:
        print(f"Error detallado: {e}")
        return None

# Ejecución
df_4090 = get_vast_human_readable("RTX 4090")

if df_4090 is not None:
    print(f"Listado detallado de RTX 4090 (Unidades legibles):")
    pd.set_option('display.max_columns', None)
    pd.set_option('display.width', 1000)
    # Mostramos los primeros 30 resultados para no saturar
    print(df_4090.head(30).to_string(index=False))

Listado detallado de RTX 4090 (Unidades legibles):
 Offer_ID               Region  GPUs  VRAM_GB  Price_$/Hr  Descarga_MB/s  Subida_MB/s  Costo_Egress_$/TB  Costo_Ingress_$/TB  Reliability_%
 31239993       California, US     1       23    0.242315          194.8         65.1               4.00                2.67           99.0
 28758521           Quebec, CA     1       23    0.254546          110.7        111.0               0.00                0.00           97.3
 32642705           France, FR     1       23    0.268056           96.8         96.9               4.00                2.67           98.3
 31129843           France, FR     1       23    0.268056          107.7         92.9               4.00                2.67           99.2
 33135922           Norway, NO     1       23    0.268519          101.5        100.8              13.65               13.65           99.7
 30950585  The Netherlands, NL     1       23    0.281389          135.0        168.9               1.33                1.33           97.6
 29907793                 , CN     1       23    0.294722          164.2        165.8               1.33                1.33           99.4
 29116657          Hungary, HU     1       23    0.301852          862.0        527.7              53.33               40.00           99.6
 26349246 British Columbia, CA     1       23    0.306722          116.2        116.2               0.00                0.00           99.6
 13430351           Norway, NO     1       23    0.308056           87.9         80.1               6.67                6.67           99.8
 30946284  The Netherlands, NL     1       23    0.308056          121.1        173.2               0.40                0.40           97.7
 28184064   North Carolina, US     1       23    0.316250          146.3        192.9               0.67                1.00           99.2
 30954111           Israel, IL     1       23    0.316926           72.1         92.3               0.00                0.00           98.9
 28363360           Taiwan, TW     1       23    0.321389          111.1         68.1               4.00                4.00           99.9
 22692661            Spain, ES     1       23    0.334722          902.9        708.8              12.00                9.33           99.9
 33005061            Italy, IT     1       23    0.338361          115.1        115.6               1.28                1.28           99.7
 28684339           Sweden, SE     1       23    0.341852          282.0        282.8              26.67               26.67          100.0
 21263072          Iceland, IS     1       23    0.348056          434.9        410.6               4.13                2.80           99.9
 26822554 British Columbia, CA     1       23    0.350722          361.4        360.2               2.67                2.67           99.9
 31611308          Hungary, HU     1       23    0.368519          928.6        681.4              26.67               26.67           99.4
 32126942          Hungary, HU     1       23    0.369852          867.2        915.8              26.67               26.67           99.6
 32699613          Hungary, HU     1       23    0.370722          657.5        554.2              26.67               26.67           97.7
 32681251          Hungary, HU     1       23    0.372056          670.4        490.1              26.67               26.67           98.9
 13351893            Texas, US     1       23    0.374907          800.2        793.9              29.33               29.33           99.8
 31825445            Texas, US     1       23    0.375185          776.5        407.5               4.00                2.67           99.8
 27242189            Texas, US     1       23    0.400926         3773.5       3571.9               0.00                0.00           99.8
  8972508          Iceland, IS     1       23    0.401037          452.6        402.5               4.13                2.80          100.0
  7527477          Iceland, IS     1       23    0.401037          425.6        417.3               0.00                0.00           99.6
 10788450          Iceland, IS     1       23    0.401037          456.4        392.9               3.07                2.05           99.9
  8966811          Iceland, IS     1       23    0.401037          332.2        315.8               0.00                0.00           99.9